spring.application.name=api

# Port du serveur
server.port=${SERVER_PORT:3001}

# ---- Datasource MySQL ----
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

